### ISSUE TITLE
Element is not defined

### ISSUE THREAD

**Issue by olivierpichon** [component/matches-selector#13]
Hi there,

Thanks for your work on `matches-selector`.

When testing some of our React Component that depends on `matches-selector`, we got the following exception:

```
> mocha --compilers js:babel-core/register --timeout 10000 app/assets/javascripts/tests/**/**.spec.js app/assets/javascripts/tests/**/**/**.spec.js


/Users/olivier/Documents/sources/outfit_repos/outfit/node_modules/matches-selector/index.js:3
var proto = Element.prototype;
            ^
ReferenceError: Element is not defined
    at Object.<anonymous> (/Users/olivier/Documents/sources/outfit_repos/outfit/node_modules/matches-selector/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/olivier/Documents/sources/outfit_repos/outfit/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

The only code I need to write to get this error is:

`import matches from 'matches-selector';`

It would be awesome if requiring this module on Node land would not raise any exception, same way it is possible to require jQuery (which is also meant for browser environment) without generating exceptions.

Thanks for your feedback guys!

**Comment by remiremi** [comment]
It'd be great if someone could merge PR #16 

In the meantime I fixed my issue by defining Element when setting up the environment.

```
global.Element = function(){};
```

**Comment by timaschew** [comment]
Just published to npm
